version: '3.7'
#THIS environment sets up all of FAS except for the main fas binary..
#  All dependencies -> HSM (vault, hm-collector, kafka), RTS (red fish sims) are all setup and active.
#  The ports are exposed to the local system.
networks:
  rts:
services:
  etcd:
    image: dtr.dev.cray.com/coreos/etcd:v3.4.7
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - rts
  firmware-action:
    build:
      context: .
      dockerfile: Dockerfile.integration.Dockerfile
    environment:
      - SMS_SERVER=http://cray-smd:27779
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - S3_ENDPOINT=http://s3
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - VAULT_SKIP_VERIFY=true
      - VAULT_ENABLED=true
      - LOG_LEVEL=TRACE
      - TRS_IMPLEMENTATION=LOCAL
      - HSMLOCK_ENABLED=true
      - STORAGE=ETCD
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    networks:
      - rts
    ports:
      - "28800:28800"
  s3:
    image: dtr.dev.cray.com/cache/nginx:1.18.0
    hostname: s3
    volumes:
      - ./Images:/usr/share/nginx/html
    ports:
      - "9000:80"
    networks:
      - rts
  vault:
    hostname: vault
    image: dtr.dev.cray.com/library/vault:1.4.2
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - rts
  vault-kv-enabler:
    image: dtr.dev.cray.com/hms/vault-kv-enabler:1.4.0
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds
    depends_on:
      - vault
    networks:
      - rts
  redis:
    image: dtr.dev.cray.com/library/redis:5.0-alpine
    hostname: hms-redfish-redis
    ports:
      - "6379:6379"
    networks:
      - rts
  hmsds-postgres:
    hostname: hmsds-postgres
    image: dtr.dev.cray.com/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    ports:
      - "5432:5432"
    networks:
      - rts
  cray-smd-init:
    image: dtr.dev.cray.com/cray/cray-smd
    environment:
      - SMD_DBHOST=hmsds-postgres
      - SMD_DBPORT=5432
    depends_on:
      - hmsds-postgres
    networks:
      - rts
    command: /entrypoint.sh smd-init
  cray-smd:
    image: dtr.dev.cray.com/cray/cray-smd
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    ports:
      - "27779:27779"
    networks:
      - rts
  zookeeper:
    image: dtr.dev.cray.com/confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - rts
  kafka:
    image: dtr.dev.cray.com/confluentinc/cp-kafka:5.4.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - rts
  cray-hms-hmcollector:
    image: dtr.dev.cray.com/cray/hms-hmcollector
    environment:
      - LOG_LEVEL=TRACE
      - SM_URL=http://cray-smd:27779
      - POLLING_ENABLED=false
      - RF_SUBSCRIBE_ENABLED=false
      - REST_PORT=80
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./configs/kafka_brokers.json:/configs/kafka_brokers.json
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    networks:
      - rts
  x9000c3s0b0:
    image: dtr.dev.cray.com/cray/cray-remote-node
    environment:
      - XNAME=x9000c3s0b0
      - PORT=:8444
      - HOST=rocket-ncn-m001.us.cray.com
      - HOSTUSER=root
      - HOSTPASSWORD=initial0
      - REDFISHUSER=root
      - REDFISHPASSWORD=initial0
    hostname: x9000c3s0b0
    ports:
      - "8444:8444"
    networks:
      - rts
  x9000c1s7b0:
    image: dtr.dev.cray.com/cray/cray-remote-node
    environment:
      - XNAME=x9000c1s7b0
      - PORT=:8445
      - HOST=sif-ncn-m001.us.cray.com
      - HOSTUSER=root
      - HOSTPASSWORD=initial0
      - REDFISHUSER=root
      - REDFISHPASSWORD=initial0
    hostname: x9000c1s7b0
    ports:
      - "8445:8445"
    networks:
      - rts
