---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fas-nexus-info
  namespace: services
data:
  nexus_endpoint: "{{ .Values.nexus.endpoint }}"
  nexus_repo: "{{ .Values.nexus.repo }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fas-cacert-info
data:
  CA_URI: "{{ .Values.hms_ca_uri }}"
