apiVersion: batch/v1
kind: Job
metadata:
  name: cray-fas-loader-{{ .Release.Revision }}
  labels:
    app: cray-fas-loader
spec:
  template:
    metadata:
      labels:
        app: cray-fas-loader
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cray-fas-loader
          image: "{{ include "cray-fas.image-prefix" .Values }}cray/cray-firmware-action:{{ include "cray-fas.imageTag" . }}"
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: LAUNCH
              value: "LOADER"
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: fw-update-s3-credentials
                  key: fw_s3_endpoint
            - name: S3_BUCKET
              value: fw-update
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fw-update-s3-credentials
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fw-update-s3-credentials
                  key: secret_key
            - name: NEXUS_ENDPOINT
              value: "{{ .Values.nexus.endpoint }}"
            - name: NEXUS_REPO
              value: "{{ .Values.nexus.repo }}"
            - name: ASSETS_DIR
              value: "/firmware"
            - name: FAS_URL
              value: "cray-fas"
            - name: API_URL
              value: "http://cray-fas"
            - name: API_SERVER_PORT
              value: ""
            - name: API_BASE_PATH
              value: ""
