name: Build and Publish Docker Images
on:
  - push # Perform a build of the contents from the branch
  - pull_request # Perform a build after merging with the target branch
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-scripts/.github/workflows/build_and_release_image.yaml@develop
    with:
      image-name: cray-firmware-action
    secrets:
      artifactory-username: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
      artifactory-token: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      cosign-gcp-project-id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
      cosign-gcp-sa-key:  ${{ secrets.COSIGN_GCP_SA_KEY }}
      cosign-key: ${{ secrets.COSIGN_KEY }}
