name: Build and Publish Docker Images
on: [push, pull_request] # Question: Should this run on push/pull request? What is the value on pull_request?
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-scripts/.github/workflows/build_and_release_image.yaml@develop
    with:
      image-name: ray-firmware-action
    secrets:
      artifactory-username: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
      artifactory-token: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      cosign-gcp-project-id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
      cosign-gcp-sa-key:  ${{ secrets.COSIGN_GCP_SA_KEY }}
      cosign-key: ${{ secrets.COSIGN_KEY }}
