name: Run Unit Tests
on: [push, pull_request]
jobs:
  run_unit_test:

    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Unit Test
        shell: bash
        run: |
          sudo apt-get install make
          make unittest