name: Run Integration Tests
on: [pull_request]
jobs:
  run_integration_test:
    uses: Cray-HPE/hms-build-scripts/.github/workflows/run_integration_test.yaml@develop
    with:
      runs-on: ubuntu-latest